XDG_DESKTOP_DIR=/home/edicsonabel/Desktop
XDG_DOWNLOAD_DIR=/home/edicsonabel/Descargas
XDG_TEMPLATES_DIR=/home/edicsonabel/Plantillas
XDG_PUBLICSHARE_DIR=/home/edicsonabel/Público
XDG_DOCUMENTS_DIR=/home/edicsonabel/Documentos
XDG_MUSIC_DIR=/home/edicsonabel/Música
XDG_PICTURES_DIR=/home/edicsonabel/Imágenes
XDG_VIDEOS_DIR=/home/edicsonabel/Vídeos
